/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *      
 */

'use strict';

/* eslint-disable no-unused-vars */

                                                           
                                 
     
                                           
     
         
       
                                                                            
                                                                            
                              
       
                             
       
                                                                     
                                            
       
                              
       
                                                                   
                                          
       
                                                       
    
     
                                                               
                                                                              
                                                   
     
                    
     
                                                                               
                                                         
     
                    
     
                                                                             
                                                                          
                                                                           
                                                                               
                                                            
     
                      
     
                                                                              
                                                                           
                                                                            
                                                   
     
                     
                                        
                                     
     
                                                                              
                                                                              
                                     
     
                         
                                        
                                     
     
                                                                             
                                                      
     
                                                          
     
                                                      
     
                         
     
                                                                                
     
                                                                   
     
                                                           
     
                                                                       
     
                                                                         
     
                                                                              
     
                                                                             
     
                        
                  
                                              
     
                                                                        
     
                                                                          
     
                                                                            
     
                                                                              
  

                                   
     
                                     
     
                                         
  

                      
                   
               
                 
                  
                 
                      
                
  

                      
                  
                             
                                    
                    
  

                          
                                    
                
  

                    
              
               
                                                    

                        
     
                                                                        
                                                                             
     
                                                  
                          
     
                                                                         
                                                                            
     
                                                  
                           
  

/**
 * Jest allows functions and classes to be used as test names in test() and
 * describe()
 */
                                      

/**
 *  Plugin: jest-styled-components
 */

                                       
          
                              
          
                     

                                           
                 
                    
                    
  

                                         
                  
                     
                                            
                                                
          
  

/**
 *  Plugin: jest-enzyme
 */
                           
        
                    
                      
        
                      
                       
                          
                                                   
                                                               
                                                             
                                                    
                  
                                           
                                 
                                                            
                          
                                   
                                                               
                          
                                                               
                          
                                       
                                 
                                
                                    
                 
                                
                                                        
          
                                          
        
                                        
  

// DOM testing library extensions https://github.com/kentcdodds/dom-testing-library#custom-jest-matchers
                              
                       
                    
                            
                      
                                                      
                                        
                                                              
                                             
                      
                                                                
                                 
                    
                             
                                            
          
                       
  

// Jest JQuery Matchers: https://github.com/unindented/custom-jquery-matchers
                               
                  
                                  
                             
                                       
                               
                                           
                                           
                                          
                                           
                              
                                             
                      
                       
                    
                     
                       
                      
                      
                    
                                   
                                      
                                                                     
  

// Jest Extended Matchers: https://github.com/jest-community/jest-extended
                                 
     
                                  
                      
    
                            
     
                                  

     
                                  
                      
    
                            
     
                                  

     
                                                                                 
     
                    

     
                                                                          
                               
     
                                  

     
                                                                   
     
                  

     
                                                                                                                       
                                
     
                                                  

     
                                                             
     
                    

     
                                                                             
                      
     
                                   

     
                                                                                                            
                               
     
                                            

     
                                                                                                       
                               
     
                                            

     
                                                                                                                                                     
                                
     
                                                     

     
                                                                
     
                      

     
                                                                    
     
                   

     
                                                                      
     
                    

     
                                                      
     
                   

     
                                                                  
     
                       

     
                                                                                              
    
                                    
                                                                                                                                                                                           
    
                       
     
                                                           

     
                                                              
     
                     

     
                                                   
     
                  

     
                                                                                       
     
                     

     
                                                                         
     
                       

     
                                                                         
     
                       

     
                                                                  
     
                   

     
                                                                
     
                  

     
                                                                                                                          
    
                          
                        
     
                                               

     
                                                               
     
                     

     
                                                                              
    
                        
     
                                  

     
                                                                                  
    
                                 
     
                                      

     
                                                                                               
    
                                 
     
                                         

     
                                                                                                   
    
                                 
     
                                         

     
                                                                                  
    
                     
     
                                   

     
                                                                                           
    
                              
     
                                       

     
                                                                                                   
    
                              
     
                                          

     
                                                                                                       
    
                              
     
                                          

     
                                                                                  
    
                                          
     
                                                

     
                                                                                             
    
                                                    
     
                                                      

     
                                                                                                     
    
                                                    
     
                                                         

     
                                                                                                         
    
                                                    
     
                                                         

     
                                                                    
     
                         

     
                                                            
     
                     

     
                                                            
     
                     

     
                                                              
     
                     

     
                                                                                                                           
    
                           
     
                                               

     
                                                                                        
    
                           
     
                                    

     
                                                                                    
    
                           
     
                                  

     
                                                                                        
    
                              
     
                                     

     
                                                                                                                            
    
                              
                          
     
                                                            

     
                                                                                               
    
                                      
     
                                               
  

                          
                       
                        
                           
                            
                                      
                             
     
                                                                          
                                       
     
                                            
     
                                                                           
                     
     
                         
     
                                                                       
                        
     
                                            
     
                                                                             
                                      
     
                                             
     
                                                                
     
                      
     
                                                                         
                                                  
     
                    
     
                                                                    
     
                                        
     
                                                                           
     
                                               
     
                                                                 
     
                                     
     
                                                                        
     
                                            
     
                                                                           
           
     
                                      
     
                                                                            
           
     
                   
     
                                                                          
                                                 
     
                     
     
                                                              
     
                        
     
                                                                         
                                                                           
     
                             
     
                                                                              
                                                                       
                                                                      
     
                                  
     
                                                                              
                                                                            
                                  
     
                            
     
                                                                     
     
                           
                     
     
                                                                               
                     
     
                                              
                                        
     
    
     
                                                                      
                                                            
     
    
     
                         
                   
     
    
     
                                            
                                      
     
    
     
                                       
                                 
     
    
     
                                           
                                     
     
    
     
                                                           
                                                     
     
                                                                             
                        
     
                                                  
     
                                                                                 
                             
     
                                                      
     
                                                                           
                   
     
                                     
     
    
     
                                                      
     
                                                                                
     
                                                 
     
                                                                                                          
     
                                                      
     
                                                                                                          
     
                                  
     
                                                                  
     
                                                               
     
                                                                  
     
                                      

                                                 
                                                                         
     
                                                                   
                                                                              
                                                                             
                                                                   
    
                         
     
                                                                  
                                                                       
     
                                                                             
                                                         
     
                                       
                                                              
 

                       
     
                                                      
    
                                                                        
                                                             
     
                                    
     
                                             
     
                                
     
                                                    
     
                                   
     
                                            
     
                               
     
                                                                      
                                                                 
     
                                  
     
                                                                               
                     
     
                                  
     
                                                     
     
                                    
     
                                                      
     
                         
     
                                                         
     
                          
     
                                                                      
                
     
                                                                  
     
                                                                        
                
     
                                               
     
                                                                 
                    
     
                                             
                                                     
                                     
     
                                                           
     
                                        
     
                                                                               
                                          
     
                                             
     
                                                                          
    
                                                                               
                                                              
    
                                                                               
                                             
     
       
                       
                        
                    
                    
     
                                                                         
                                                                    
     
                                         
     
                                                                             
                                                              
     
                                       
     
                                                                            
                                                                              
     
                                 

     
                                                                          
                                                                            
                                                                    
     
                                                 

     
                                                                  
                       
     
                      
     
                                                                           
                                        
     
                       
     
                                                 
     
                           
     
                                                                              
                                          
     
                                             
     
                                                                              
                                          
    
                                      
     
                                         
     
                                                                             
                                                                            
           
     
                               
     
                                                                             
                                                                         
             
     
                                                                  
     
                                                                             
                                                                               
                  
     
                                             
     
                                                                        
                                                                     
                                      
     
                                  
     
                                                                             
     
                                  
     
                                                                        
                        
     
        
                   
                       
                              
                          
     
                                                                                       
                                                                                  
     
                                              
  

                    
                       
  

/** Runs this function after every test inside this context */
                           
                                            
                  
        
/** Runs this function before every test inside this context */
                            
                                            
                  
        
/** Runs this function after all tests have finished inside this context */
                          
                                            
                  
        
/** Runs this function before any tests have started inside this context */
                           
                                            
                  
        

/** A context for grouping tests together */
                       
     
                                                                                   
     
                                             

     
                                 
     
                                                 

     
                                     
     
                                                 

     
                                                                      
    
                                 
     
       
                                                                   
      
                       
                                                  
                    
            
  

/** An individual test unit */
                 
     
                            
    
                                       
                           
                                                           
     
   
                       
                                               
                    
          

     
                       
    
                                       
                           
                                                           
     
       
                       
                                               
                    
      
         
                                                                     
        
                         
                                                    
                      
              
    

     
                           
    
                                       
                           
                                                           
     
       
                       
                                               
                    
          

     
                                                  
    
                                       
     
                           

     
                              
    
                                       
                           
                                                           
     
             
                       
                                               
                    
          

     
                                                                      
    
                                 
     
       
                                                                   
      
                       
                                                  
                    
            
  

                     
                     
                                            
                  
        
/** An individual test unit */
                            
/** A disabled group of tests */
                                       
/** A focused group of tests */
                                       
/** A disabled individual test */
                           
/** A disabled individual test */
                             

                               
                                         
                                         
                                      
                                     
                                       
  

                                               
// eslint-disable-next-line no-unused-vars
                                       
                                           
// eslint-disable-next-line no-unused-vars
                                                  

                                
                      
                      
                       
                     
                 
                   
               
                                                  
                                   
                             
                  
          
                    
                    
                 
                
                  
    
  

                               
          
             
                                     
                                   
                                  
                                  
              
                       
  

                                                             

/** The expect function is used every time you want to test a value */
                     
                                                            
   
              
                     
                     
                        
                           
                            
                                      
                             

                                                         
                                                        
                                                                        
                                                                    
                                               
                        
                                                
                  
                                                     
                                          
                                                                             
                                          
                                                 
        
                                                                    
                                            
                                                
                                                       
    
  

/** Holds all functions related to manipulating test runner */
                                 
